INSERT INTO `section`(id,name) values (1, 'section1')
INSERT INTO `section`(id,name) values (2, 'section2')
INSERT INTO `section`(id,name) values (3, 'section3')
INSERT INTO `section`(id,name) values (4, 'section4')
INSERT INTO `section`(id,name) values (5, 'section5')

INSERT INTO `user`(id,email,name,password) values (1, 'asd@o2.com', 'ian', 'passw!1Aa3b')
INSERT INTO `user`(id,email,name,password) values (2, 'asdd@o2.com', 'johhn', 'pasS2sw!1Aa3b')
INSERT INTO `user`(id,email,name,password) values (3, 'assd@o2.com', 'george', 'pAassw!1Aa3b')
INSERT INTO `user`(id,email,name,password) values (4, 'absd@o2.com', 'tom', 'Passw!1SAa3b')

INSERT INTO thread (id,name,section_id) values (1, 'thread1', 1)
INSERT INTO thread (id,name,section_id) values (2, 'thread2', 2)
INSERT INTO thread (id,name,section_id) values (3, 'thread3', 2)
INSERT INTO thread (id,name,section_id) values (4, 'thread4', 1)
INSERT INTO thread (id,name,section_id) values (5, 'thread5', 1)
INSERT INTO thread (id,name,section_id) values (6, 'thread6', 2)
INSERT INTO thread (id,name,section_id) values (7, 'thread7', 3)

INSERT INTO post(id,content, thread_id, user_id) values(1, 'post1', 1, 1)
INSERT INTO post(id,content, thread_id, user_id) values(2, 'post2', 1, 2)
INSERT INTO post(id,content, thread_id, user_id) values(3, 'post3', 1, 3)
INSERT INTO post(id,content, thread_id, user_id) values(4, 'post4', 1, 1)
INSERT INTO post(id,content, thread_id, user_id) values(5, 'post5', 2, 1)

